- Link to dataset: https://www.kaggle.com/iasonaskatechis/comic-books-current-values-and-other-data?select=comics_data.csv

In [1]:
!pip install yellowbrick

Collecting yellowbrick
  Using cached yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
Requirement already satisfied: scipy>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from yellowbrick) (1.6.2)
Requirement already satisfied: cycler>=0.10.0 in c:\programdata\anaconda3\lib\site-packages (from yellowbrick) (0.10.0)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from yellowbrick) (3.3.4)
Requirement already satisfied: scikit-learn>=0.20 in c:\programdata\anaconda3\lib\site-packages (from yellowbrick) (0.24.1)
Collecting numpy<1.20,>=1.16.0
  Using cached numpy-1.19.5-cp38-cp38-win_amd64.whl (13.3 MB)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from cycler>=0.10.0->yellowbrick) (1.15.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (8.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.4.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=0.20->yellowbrick) (2.1.0)
Requirement already satisfied: joblib>=0.11 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=0.20->yellowbrick) (1.0.1)
Installing collected packages: numpy, yellowbrick
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
Successfully installed numpy-1.19.5 yellowbrick-1.3.post1

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.cluster import KMeans
from io import open
from yellowbrick.cluster import KElbowVisualizer

pd.options.display.max_columns = 150
plt.rcParams["figure.figsize"] = (20,10)

In [10]:
df = pd.read_csv("resources/comics_data.csv", sep=',')

In [11]:
df.head(2)

,Unnamed: 0,title,title_link,issue_link,cover_link,issue,cover_date,cover_price,current_value,hist_prices_link,searched,owned,pages,rating,rating_count,ISBN-UPC,est_print_run,variant_of,preview,synopsis,contributors_names,contributors_roles,characters,pub_id,volume,years,issues_total,pub_name,pub_titles_total,pub_issues_total
0,0,'Mazing Man,/series/4036/0/dc-comics-mazing-man,https://comicbookrealm.com/series/4036/54341/d...,/cover-scan/acb40c8a57d50781194e37be2a94b3d5/l...,# 1,Jan '86,$0.75,$3.00,/comic.php?a=historical&comic=54341?keepThis=t...,1259,181,32.0,0.0,0,NaN,NaN,NaN,NaN,1st appearance of 'Mazing Man,"['Stephen Destefano', 'Alan Gold', 'Nansi Hool...","['Pencils-CoverArt', 'Editor', 'Colors', 'Cove...","[[""'Mazing Man"", '/character-photos/character_...",1.0,NaN,1986,15.0,DC Comics,4688,57043
1,1,'Mazing Man,/series/4036/0/dc-comics-mazing-man,https://comicbookrealm.com/series/4036/54350/d...,/cover-scan/293f4e231eccb71ad6e6bc3fe3e49c4f/l...,# 10,Oct '86,$0.75,$3.00,/comic.php?a=historical&comic=54350?keepThis=t...,182,70,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,no contributors assigned,no contributors assigned,no characters assigned,1.0,NaN,1986,15.0,DC Comics,4688,57043

Removing unnecessary fields for this analysis

In [12]:
df.drop(df.columns[2:5], axis=1, inplace=True)

df.head(1)

,Unnamed: 0,title,issue,cover_date,cover_price,current_value,hist_prices_link,searched,owned,pages,rating,rating_count,ISBN-UPC,est_print_run,variant_of,preview,synopsis,contributors_names,contributors_roles,characters,pub_id,volume,years,issues_total,pub_name,pub_titles_total,pub_issues_total
0,0,'Mazing Man,# 1,Jan '86,$0.75,$3.00,/comic.php?a=historical&comic=54341?keepThis=t...,1259,181,32.0,0.0,0,NaN,NaN,NaN,NaN,1st appearance of 'Mazing Man,"['Stephen Destefano', 'Alan Gold', 'Nansi Hool...","['Pencils-CoverArt', 'Editor', 'Colors', 'Cove...","[[""'Mazing Man"", '/character-photos/character_...",1.0,NaN,1986,15.0,DC Comics,4688,57043

In [13]:
df.drop(df.columns[6], axis=1, inplace=True)

df.head(1)

,Unnamed: 0,title,issue,cover_date,cover_price,current_value,searched,owned,pages,rating,rating_count,ISBN-UPC,est_print_run,variant_of,preview,synopsis,contributors_names,contributors_roles,characters,pub_id,volume,years,issues_total,pub_name,pub_titles_total,pub_issues_total
0,0,'Mazing Man,# 1,Jan '86,$0.75,$3.00,1259,181,32.0,0.0,0,NaN,NaN,NaN,NaN,1st appearance of 'Mazing Man,"['Stephen Destefano', 'Alan Gold', 'Nansi Hool...","['Pencils-CoverArt', 'Editor', 'Colors', 'Cove...","[[""'Mazing Man"", '/character-photos/character_...",1.0,NaN,1986,15.0,DC Comics,4688,57043

In [14]:
df["searched"].value_counts()

23       3121
25       3115
22       3107
19       3073
21       3054
         ...
7344        1
10082       1
16225       1
12043       1
5500        1
Name: searched, Length: 9263, dtype: int64

In [15]:
df["title"].value_counts()

Amazing Spider-Man                     2455
March of Comics                        1791
Batman                                 1757
Detective Comics                       1528
Vampirella                             1447
                                       ...
MAD: Unite the Stupid                     1
Doctor Who: Dave Gibbons Collection       1
Onyx: Fight                               1
Long Count                                1
Weeding                                   1
Name: title, Length: 58761, dtype: int64

Statistical analysis of data

In [16]:
pd.options.display.float_format = "{:.2f}".format

df.describe()

,Unnamed: 0,searched,owned,pages,rating,rating_count,pub_id,issues_total,pub_titles_total,pub_issues_total
count,461301.00,461301.00,461301.00,208011.00,461301.00,461301.00,461301.00,456401.00,461301.00,461301.00
mean,230650.00,472.51,54.49,53.80,0.38,0.14,1389.15,105.15,2039.69,20774.51
std,133166.27,1832.64,157.03,195.46,1.22,0.58,1766.45,215.98,2620.83,25262.64
min,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00
25%,115325.00,46.00,1.00,32.00,0.00,0.00,2.00,8.00,91.00,811.00
50%,230650.00,119.00,6.00,32.00,0.00,0.00,559.00,28.00,517.00,6574.00
75%,345975.00,343.00,33.00,36.00,0.00,0.00,2960.00,99.00,4688.00,57043.00
max,461300.00,224080.00,6478.00,75960.00,5.00,15.00,8253.00,1801.00,7285.00,65535.00

In [17]:
df['pages'].value_counts()

32.00      115540
36.00       18757
28.00        8952
52.00        6664
48.00        6571
            ...
1952.00         1
410.00          1
1.50            1
305.00          1
706.00          1
Name: pages, Length: 590, dtype: int64